Hw02 express
BokovRoman/nodejs-homework-rest-api pull request #3
Opened 2021-10-31 18:28 UTC by BokovRoman

2021-10-31 18:34 UTC, KirillKulakow commented on package.json
> +    "react-router-dom": "^5.3.0"
зачем тебе роутер с реакта?

2021-10-31 18:40 UTC, KirillKulakow commented on schemas/contacts.js
> +      /^[a-zA-Zа-яА-Я]+(([' -][a-zA-Zа-яА-Я ])?[a-zA-Zа-яА-Я]*)*$/,
пропустил букву ё в регулярке

2021-10-31 18:46 UTC, KirillKulakow commented on middlewares/index.js
> +// const validation = require("./validation");
удалить

2021-10-31 18:47 UTC, KirillKulakow commented on controllers/contacts.js
> +const contactsOperation = require('../model/contacts')
деструктурируй

2021-10-31 18:53 UTC, KirillKulakow commented on model/contacts/listContacts.js
> +const listContacts = async () => {
зачем тебе данная функция? если ты в ней просто вызываешь другую функцию?

2021-10-31 18:54 UTC, KirillKulakow commented on model/contacts/removeContactById.js
> +  contacts.splice(idx, 1)
можно просто написать const removeContact = contacts.splice(idx, 1)

2021-10-31 18:54 UTC, KirillKulakow commented on model/contacts/updateContactById.js
> +  const [result] = contacts.filter((contact) => contact.id === id)
используй find

2021-10-31 18:58 UTC, KirillKulakow commented on model/contacts/updateContactById.js
> +    Object.assign(result, body)
ты выполняешь функцию но никуда не записываешь ответ и потом просто записываешь тот же список что и был

2021-10-31 18:59 UTC, KirillKulakow commented on model/contacts/updateContacts.js
> +  await fs.writeFile(contactsPath, JSON.stringify(newContact))
await и фигурные скобки не обязательны

2021-10-31 18:59 UTC, KirillKulakow commented on bin/server.js
> +// console.log(process.env)
удалить

2021-10-31 19:01 UTC, KirillKulakow requested changes
Need fix

2021-10-31 19:54 UTC, BokovRoman commented on package.json
> +    "react-router-dom": "^5.3.0"
удалил роутер

2021-10-31 19:54 UTC, BokovRoman commented on schemas/contacts.js
> +      /^[a-zA-Zа-яА-Я]+(([' -][a-zA-Zа-яА-Я ])?[a-zA-Zа-яА-Я]*)*$/,
добавил Ё в регулярку

2021-10-31 19:54 UTC, BokovRoman commented on middlewares/index.js
> +// const validation = require("./validation");
удалил

2021-10-31 19:55 UTC, BokovRoman commented on controllers/contacts.js
> +const contactsOperation = require('../model/contacts')
не разобрался, что деструктуризировать и зачем переименовывать функции

2021-10-31 19:56 UTC, BokovRoman commented on model/contacts/listContacts.js
> +const listContacts = async () => {
из прошлого модуля(делал как Богдан, на уроке, показывал пример переиспользования, захотел применить к текущему заданию+ попрактиковаться дополнительно)

2021-10-31 19:56 UTC, BokovRoman commented on model/contacts/removeContactById.js
> +  contacts.splice(idx, 1)
исправил

2021-10-31 19:57 UTC, BokovRoman commented on model/contacts/updateContactById.js
> +  const [result] = contacts.filter((contact) => contact.id === id)
использовал find

2021-10-31 19:57 UTC, BokovRoman commented on model/contacts/updateContactById.js
> +    Object.assign(result, body)
не сильно понял, что нужно исправить

2021-10-31 19:57 UTC, BokovRoman commented on model/contacts/updateContacts.js
> +  await fs.writeFile(contactsPath, JSON.stringify(newContact))
исправил

2021-10-31 19:58 UTC, BokovRoman commented on bin/server.js
> +// console.log(process.env)
удалено

2021-10-31 20:03 UTC, KirillKulakow commented on model/contacts/updateContactById.js
> +  const [result] = contacts.find((contact) => contact.id === id)
find в данном случае возвращает обьект - нужно просто написать const result

2021-10-31 20:06 UTC, KirillKulakow commented on model/contacts/updateContactById.js
> +    Object.assign(result, body)
По порядку выполнения данной функции:
1) берешь контакты в переменную contacts
2) находишь контакт и записываешь в переменную result
3) если контакт найден - просто выполняешь функцию слияния объектов, без записи в переменную
4) обновляешь список контактов - контактами которые у тебя остались с первого пункта (т. е. изменений нет)

2021-10-31 20:08 UTC, KirillKulakow commented on routes/api/contacts.js
> +const { contactsSchema } = require('../../schemas')
ты нигде не используешь валидацию по схеме - нужно исправить

2021-10-31 20:11 UTC, KirillKulakow commented on controllers/contacts.js
> +const contactsOperation = require('../model/contacts')
вместо contactsOperation было бы лучше написать { listContacts,  getContactById, addContact, removeContactById, updateContactById }

2021-10-31 20:16 UTC, BokovRoman commented on controllers/contacts.js
> +const contactsOperation = require('../model/contacts')
а можно оставить? , т.к. в данном случае  мне с деструктуризацией  не такой читабельный код будет.

2021-10-31 20:17 UTC, BokovRoman commented on model/contacts/updateContactById.js
> +  const [result] = contacts.find((contact) => contact.id === id)
исправил

2021-10-31 20:19 UTC, BokovRoman commented on routes/api/contacts.js
> +const { contactsSchema } = require('../../schemas')
принято, исправил

2021-10-31 20:30 UTC, BokovRoman commented on model/contacts/updateContactById.js
> +    Object.assign(result, body)
надеюсь, что теперь правильно

2021-11-01 19:32 UTC, KirillKulakow commented on controllers/contacts.js
> +const contactsOperation = require('../model/contacts')
Окей, можно - но имей ввиду что в дальнейшем ты будешь писать код не только для себя)

2021-11-01 20:27 UTC, KirillKulakow commented on model/contacts/updateContactById.js
> +  const result = contacts.find((contact) => contact.id === id)
поправь проверку - так как в params тебе всегда приходит строка а в json у тебя кое где хранятся цифры

2021-11-02 20:06 UTC, BokovRoman commented on model/contacts/updateContactById.js
> +  const result = contacts.find((contact) => contact.id === id)
I need your help.) Помоги разобраться с этой ошибкой, что не так я прописал?

2021-11-03 20:23 UTC, BokovRoman commented on model/contacts/updateContactById.js
> +  const result = contacts.find((contact) => contact.id === id)
готово

2021-11-03 20:30 UTC, KirillKulakow approved these changes

2021-11-03 20:34 UTC, merged