Hw03 mongodb
BokovRoman/nodejs-homework-rest-api pull request #4
Opened 2021-11-06 16:23 UTC by BokovRoman

Проверь, пожалуйста

2021-11-06 17:48 UTC, KirillKulakow commented on models/contacts.js
> +const contactsSchemaJoi = Joi.object({
данная валидация нигде не используется - внеси правки

2021-11-06 17:52 UTC, KirillKulakow requested changes
Need fix

2021-11-06 19:12 UTC, BokovRoman commented on models/contacts.js
> +const contactsSchemaJoi = Joi.object({
добавил валидацию

2021-11-07 07:50 UTC, KirillKulakow approved these changes

2021-11-07 07:54 UTC, merged