Hw04 auth
BokovRoman/nodejs-homework-rest-api pull request #6
Opened 2021-11-13 15:30 UTC by BokovRoman

Проверь, пожалуйста

2021-11-13 18:00 UTC, KirillKulakow commented on controllers/contacts.js
> +// const listContacts = async (req, res) => {
удалить

2021-11-13 18:01 UTC, KirillKulakow commented on controllers/contacts.js
> +// const getContactById = async (req, res) => {
удалить

2021-11-13 18:01 UTC, KirillKulakow commented on controllers/contacts.js
> +//   const contact = await Contact.create(req.body)
удалить

2021-11-13 18:01 UTC, KirillKulakow commented on controllers/contacts.js
> +// const removeContactById = async (req, res) => {
удалить

2021-11-13 18:02 UTC, KirillKulakow commented on controllers/contacts.js
> +// const updateContactById = async (req, res) => {
удалить

2021-11-13 18:02 UTC, KirillKulakow commented on controllers/contacts.js
> +//   const { contactId } = req.params
удалить

2021-11-13 18:03 UTC, KirillKulakow commented on controllers/contacts.js
> +  console.log(contact)
удалить

2021-11-13 18:06 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    throw new Unauthorized('Not authorized')
эта ошибка остается необработанной - так как она не внесена в try catch

2021-11-13 18:09 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    res.status(401).json({
почему здесь нельзя использовать throw new Unauthorized('Not authorized'), если ты его уже начал использовать?

2021-11-13 18:11 UTC, KirillKulakow commented on middlewares/authenticate.js
> +  if (!authorization) {
можно перед этой строкой открыть try , вместо строки 25
А уже внутри catch возвращать:
```
  const { status = 500, message = err.message } = error;
  res.status(status).json({ status: 'error', code: status, message })
```

2021-11-13 18:17 UTC, KirillKulakow requested changes
Need fix

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +// const listContacts = async (req, res) => {
сделано

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +// const getContactById = async (req, res) => {
сделано

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +//   const contact = await Contact.create(req.body)
сделано

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +// const removeContactById = async (req, res) => {
сделано

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +// const updateContactById = async (req, res) => {
сделано

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +//   const { contactId } = req.params
сделано

2021-11-13 20:52 UTC, BokovRoman commented on controllers/contacts.js
> +  console.log(contact)
сделано

2021-11-13 20:56 UTC, BokovRoman commented on middlewares/authenticate.js
> +    throw new Unauthorized('Not authorized')
испарвлено, внес в try catch

2021-11-13 20:59 UTC, BokovRoman commented on middlewares/authenticate.js
> +    res.status(401).json({
использовал, исправил

2021-11-14 11:18 UTC, KirillKulakow commented on middlewares/authenticate.js
> +  if (!authorization) {
почему не внес правки? Если я не прав в данном утверждении - я открыт для обсуждений

2021-11-14 15:36 UTC, BokovRoman commented on middlewares/authenticate.js
> +  if (!authorization) {
Делал все по видеоуроку Богдана, он эту мидлвару не выносил в  try catch.
Так как сделал я есть ошибкой?

2021-11-14 18:42 UTC, BokovRoman commented on middlewares/authenticate.js
> +  if (!authorization) {
исправил

2021-11-14 20:14 UTC, KirillKulakow approved these changes

2021-11-14 20:21 UTC, merged